services:
  speech_therapy_gateway:
    profiles: ["all","gateway"]
    image: docker.io/library/nginx:latest
    # image: speech_therapy_server:latest
    container_name: speech_therapy_gateway
    ports:
       - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - speech_therapy

  speech_therapy_web:
    profiles: ["all","frontend"]
    image: ghcr.io/homeshw/speech_therapy_web:latest
    # image: speech_therapy_web:latest
    container_name: speech_therapy_web
    ports:
      - "3000:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - speech_therapy

  speech_therapy_server:
    profiles: ["all","backend"]
    image: ghcr.io/homeshw/speech_therapy_server:latest
    # image: speech_therapy_server:latest
    container_name: speech_therapy_server
    env_file:
      .env
    ports:
      - "5001:5001"
    volumes:
      - ./config.json:/app/config.json
      - ./audio_files:/app/audio_files
    networks:
      - speech_therapy

networks:
  speech_therapy: