services:
  speech_therapy_web:
    image: ghcr.io/homeshw/speech_therapy_web:latest
    # image: speech_therapy_web:latest
    container_name: speech_therapy_web
    ports:
      - "3000:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
    networks:
      - speech_therapy

  speech_therapy_server:
    image: ghcr.io/homeshw/speech_therapy_server:latest
    # image: speech_therapy_server:latest
    container_name: speech_therapy_server
    env_file:
      .env
    ports:
      - "5001:5001"
    volumes:
      - ./config.json:/app/config.json
      - ./audio_files:/app/audio_files
    networks:
      - speech_therapy

networks:
  speech_therapy: