services:
  speech_therapy_gateway:
    profiles: ["all","gateway"]
    image: docker.io/library/nginx:latest
    # image: speech_therapy_server:latest
    container_name: speech_therapy_gateway
    depends_on:
      - speech_therapy_web
    ports:
       - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificates/server.crt:/etc/nginx/ssl/server.crt
      - ./certificates/server.key:/etc/nginx/ssl/server.key
    networks:
      - speech_therapy

  speech_therapy_web:
    profiles: ["all","frontend"]
    image: ghcr.io/homeshw/speech_therapy_web:latest
    # image: speech_therapy_web:latest
    container_name: speech_therapy_web
    depends_on:
      - speech_therapy_server
    ports:
      - "3000:80"
    volumes:
      - ./config.js:/usr/share/nginx/html/config.js
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - speech_therapy

  speech_therapy_server:
    profiles: ["all","backend"]
    image: ghcr.io/homeshw/speech_therapy_server:latest
    # image: speech_therapy_server:latest
    container_name: speech_therapy_server
    depends_on:
      - mongo
    env_file:
      .env
    ports:
      - "5001:5001"
    volumes:
      - ./config.json:/app/config.json
      - ./audio_files:/app/audio_files
    networks:
      - speech_therapy

  mongo:
    profiles: ["all","database"]
    container_name: speech_therapy_mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: audioclips
    volumes:
      - mongo_data:/data/db
    networks:
      - speech_therapy

  mongo-express:
    profiles: ["all","database"]
    container_name: speech_therapy_mongo_express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - speech_therapy

volumes:
  mongo_data:

networks:
  speech_therapy: